name: mdm_admin_panel
description: Flutter-based admin panel for MDM system

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Framework
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296

  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^12.1.3

  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Authentication
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0

  # Charts & Visualization
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.2.7
  syncfusion_flutter_datagrid: ^23.2.7

  # Date & Time
  intl: ^0.18.1
  timeago: ^3.6.1

  # File Handling
  file_picker: ^6.1.1
  path_provider: ^2.1.2

  # Utils
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.2

  # Maps (for device location)
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

  # Notifications
  flutter_local_notifications: ^16.3.2

  # Responsive
  responsive_framework: ^1.1.1
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
